<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>fan</groupId>
        <artifactId>fancy-parent</artifactId>
        <version>4.0.1</version>
    </parent>
    <artifactId>fancy-toolkit</artifactId>
    <version>2.0.0</version>

    <name>fancy-toolkit</name>
    <description>General-purpose Java utility toolkit.</description>
    <url>https://github.com/Fan223/fancy-toolkit</url>
    <inceptionYear>2022</inceptionYear>
    <licenses>
        <license/>
    </licenses>

    <developers>
        <developer>
            <id>Fan</id>
            <name>Fancy</name>
            <email>fanj.zh@foxmail.com</email>
            <url>https://fan223.cn</url>
        </developer>
    </developers>
    <scm>
        <connection>scm:git:https://github.com/Fan223/fancy-toolkit.git</connection>
        <developerConnection>scm:git:git@github.com:Fan223/fancy-toolkit.git</developerConnection>
        <url>https://github.com/Fan223/fancy-toolkit</url>
        <tag/>
    </scm>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <!-- 配置 Lombok 注解处理器 -->
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-source</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
